### ISSUE TITLE
Size tap targets appropriately

### ISSUE THREAD

**Issue by McPringle** [heiseonline/shariff#137]
On smartphones the buttons may be too small for a user to easily tap on a touchscreen. Consider making these tap targets larger to provide a better user experience. Google suggests a minimal height of 7 mm (48 CSS pixels) and a minimal margin to the next tap target of 5 mm (32 CSS pixels).

If you don't follow this rule, Google PageSpeed will rate the user experience of the site down by 3%.

https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately

**Comment by craiq** [comment]
Can't reproduce your error.
Added following lines to the Page Header of the demo:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>dt,dd{word-wrap:break-word;}</style>
```
and got 100/100
testet with https://developers.google.com/speed/pagespeed/insights/

**Comment by McPringle** [comment]
Hi @craiq 

Thanks for trying to reproduce. In my HTML the viewport is already defined. Your style doesn't do anything because Shariff generates HTML code with `ul` and `li`. Your suggested `word-wrap` property won't work there.

On my website Google PageSpeed still complains about tap target size: [Google PageSpeed](https://developers.google.com/speed/pagespeed/insights/?hl=en&utm_source=wmx&utm_campaign=wmx_otherlinks&url=https%3A%2F%2Fwww.fihlon.ch%2F)]

I hope your PR will be accepted soon, so I can compare my website with your modified demo website. Actually the demo website isn't mobile ready:
![demo website on mobile device](https://www.fihlon.ch/tmp/shariff-1.png)

There is a viewport problem, too. In desktop browsers everything is working fine:
![desktop browser example](https://www.fihlon.ch/tmp/shariff-3.png)

But on mobile devices (tested with two different iPhones and iOS Simulator) the buttons don't wrap:
![mobile browser example](https://www.fihlon.ch/tmp/shariff-2.png)

**Comment by craiq** [comment]
The style was just for the demo.
But I can confirm your problem now. It just happens when you have enough elements in your shariff and I just see it in pagespeed insights. So its a problem of the pagespeed insights renderer not taking care of "flex-wrap: wrap". flex-flow couldn't fix it too.
In firefox, chrome or chrome on Android the problem don't exist.
So if you want 100/100 you need to get rid of the flex boxes.
You can take a look [here](https://github.com/craiq/shariff/). Thats how I've done it.

Another small argument for my css tweak @compeak ;)
