### ISSUE TITLE
Feature to add Instagram

### ISSUE THREAD

**Issue by ottovb** [heiseonline/shariff#144]
Hi all,
I really would like to add instagram.
I do not have the programming skills yet to add this my self.

I would really appreciate if someone could point out how to do this or if it would be added in the base code.
Kind regards,
Otto van Bruggen

**Comment by startef** [comment]
We got the same question a couple of times on our WordPress plugin forum, so I'm just going to copy and paste my answer from there:

There is currently no way to add Instagram, because they simply just do not support any interaction outside of their mobile app.

Quote from the official Instagram API docs:

>At this time, uploading via the API is not possible. We made a conscious choice not to add this for the following reasons:
>Instagram is about your life on the go – we hope to encourage photos from within the app.
>We want to fight spam & low quality photos. Once we allow uploading from other sources, it's harder to control what comes into the Instagram ecosystem.
>All this being said, we're working on ways to ensure users have a consistent and high-quality experience on our platform.

Therefore it is very unlikely that they are ever going to add a way for posting pictures without using their mobile app.

JP

**Comment by 5t0rmr1d3r** [comment]
Is this still uptodate? = no way to integrate instagram?

**Comment by richard67** [comment]
I just checked and it seems it is still up to date.

**Comment by wertzuiop123** [comment]
No change on the instagram status?

**Comment by compeak** [comment]
https://developers.facebook.com/docs/instagram-api/reference/media/

> Creating: This operation is not supported.
