### ISSUE TITLE
release files also with bower support?

### ISSUE THREAD

**Issue by tbba** [heiseonline/shariff#261]
no bug, just a thought:

If there was a "release" version (with the ready minified complete CSS and JS, not zipped) with bower support, updates could be conveniently tracked automatically with bower. 

Alternatively, the build folder wasn't that bad.

(For the small projects and lazy/unexperienced coders, where you do not want to setup/run compilers but want to enjoy bower auto-update support.)

**Comment by core23** [comment]
[Bower](https://bower.io/) is dead:

>  ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!

**Comment by tbba** [comment]
Got that. Bower might be EOL, but not for everyone - yet. 
(Webpack is annoying to set up where project timelines do not account much time for tooling/setup.)

All I want to say: Limiting use-options makes shariff less attractive?

**Comment by liayn** [comment]
@core23 
We do not need a bower version anymore, since moving from bower to npm packages is easy (did so with a lot of projects recently) and does not require anything like yarn or webpack, just some path adjustments where you use the libs.

I do agree with @tbba though that it would at least be nice to have a ready to use `dist` folder when requiring shariff via npm. Keep in mind that we use npm here in non-JS projects, where we just use it to gather the required libs for frontend. So basically some job (be it a Makefile, grunt, gulp, you name it) simply copies those required `dist` files to the target application.

**Comment by compeak** [comment]
> I do agree with @tbba though that it would at least be nice to have a ready to use dist folder when requiring shariff via npm.

@liayn The npm releases do contain build artifacts:

```
~$ mkdir sharifftest
~$ cd sharifftest/
~$ npm init
[...]
~$ npm install shariff --save
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN sharifftest@1.0.0 No description
npm WARN sharifftest@1.0.0 No repository field.

+ shariff@2.0.4
added 3 packages in 1.608s
~$ ls node_modules/shariff/dist/
fontawesome-webfont.eot    fontawesome-webfont.ttf    fontawesome-webfont.woff2  shariff.complete.js        shariff.min.js
fontawesome-webfont.svg    fontawesome-webfont.woff   shariff.complete.css       shariff.min.css
```
We removed the build artifacts from the repository. Travis handles the build process now.

**Comment by liayn** [comment]
@compeak Indeed the dist is now there via npm too. For some reason that was not the case back then. Good to know.

**Comment by compeak** [comment]
Closing in favour of #285.
