### ISSUE TITLE
Dead email link in white theme

### ISSUE THREAD

**Issue by Anke** [heiseonline/shariff#289]
In the white theme - on my website as well as on your demo page - the email link is `http://www.heise.de/?view=mail` instead of `mailto:foo@example.com?subject=Shariff demo page&body=http://heise.de/`.

**Comment by richard67** [comment]
@Anke Therev is no relation between the theme and the email link.

The email link `?view=mail` (which will be completed by the current URL) is the default value of option `data-mail-url`, see documentation [README-de.md](https://github.com/heiseonline/shariff/blob/develop/README-de.md) or [README.md](https://github.com/heiseonline/shariff/blob/develop/README.md).

If you want another email link you have to specify the `data-mail-url` in your shariff element.

In the heiseonline shariff demo, the 3rd example from top shows an example for that.

The example with `data-theme=white` in the demo (5th from top) does not use the `data-mail-url` option, and so the default is used.

So unless you provide a more detailled description on a really wrong function of Shariff, I would not regard this issue here as a bug.

But I am not an official maintainer. I am just someone who in the recent months contributed a bit to Shariff.

So some maintainer has to decide if this is a bug here or not, unless you decide yourself to close this issue because my explanation helped you.

P.S.: If more convenient for you I can also answer in German. I am German myself and use English here only because this software project has international users.

**Comment by Anke** [comment]
Hallo Richard,

Thanks for your quick response. I'm not saying it's a bug, and I'm just a designer, not a programming expert, but actually there isn't much you can do wrong with the data-attributes, is there?

After numerous browser and CMS cache dumps the "mailto:" is finally accepted and so is my mailbody text. However my custom subject is still being ignored and replaced by the page title, and I can't seem to find the error. 

These are my data attributes:

```
<div class="shariff" 
     data-orientation="vertical" 
     data-theme="white"
     data-services="[
       &quot;whatsapp&quot;,
       &quot;threema&quot;,
       &quot;facebook&quot;,
       &quot;twitter&quot;,
       &quot;googleplus&quot;,
       &quot;xing&quot;,
       &quot;linkedin&quot;,
       &quot;mail&quot;,
       &quot;info&quot;]" 
     data-lang="de"
     data-mail-body="Hier gibt es aktuelle und sehr ausführliche Meldungen über Giftköderfunde: {url}"
     data-mail-subject="Aktuelle Giftködermeldungen"
     data-mail-url="mailto:">
</div>
``` 

PS: I'll stick to English in case other experience the same problem

**Comment by richard67** [comment]
The issue with data-mail-subject has already been reported with issue no. #290 and the solution has been proposed with pull request #291 .

**Comment by Anke** [comment]
Dankeschön!
