### ISSUE TITLE
data-mail-subject doesn't seem to work. Module uses always data-title

### ISSUE THREAD

**Issue by Williwurstig** [heiseonline/shariff#290]
`<div class="myshariff" data-mail-body="Link: {url}" data-mail-subject="This is the subject" data-mail-url="mailto:">`
output:
`<a href="mailto:?subject=Pagetitle&amp;body=Link%3A%0Ahttp%3A%2F%2Ftestdomain.de" title="Per E-Mail versenden" role="button" aria-label="Per E-Mail versenden"><span class="fa fa-envelope"></span><span class="share_text">mail</span></a>`

**Comment by richard67** [comment]
I can confirm this, see discussion here: [https://github.com/heiseonline/shariff/issues/58#issuecomment-364643606](https://github.com/heiseonline/shariff/issues/58#issuecomment-364643606).

I've tested and checked the source code. It seems that either the readme docs are not up to date, or the functionality is not implemented by mistake, because the option "data-mail-subject" is not used at all in the code.

**Comment by richard67** [comment]
Pull request is #291 .

**Comment by richard67** [comment]
@Williwurstig Please check if #291 solves your issues, and comment there the result. You can find links to packages for testing in the description of #291 .

**Comment by richard67** [comment]
@compeak Now as PR #291 is merged, can this issue here be closed. Or should it stay open until the change has been released? Or should we ask @Williwurstig to close it after he has tested the PR either with the packages I provided or after a new release?

**Comment by Williwurstig** [comment]
patch works, issue closed.
