### ISSUE TITLE
No <title> breaks shariff-javascript

### ISSUE THREAD

**Issue by pxamike** [heiseonline/shariff#294]
I noticed that when <title>-tag is missing on a webpage, no share-icon appears and the shariff-javascript generates an error: "TypeError: this[0] is undefined[Learn More] app.min.js:29:904"

Attached is a html-file based on http://heiseonline.github.io/shariff/ but with js/css path externalised and the title disable to prove the issue, which can be run locally in your browser.

[shariff-test.zip](https://github.com/heiseonline/shariff/files/1731004/shariff-test.zip)

(Normally, every page should have a title-tag, but perhaps it's a good idea to make shariff sturdier against this.)

**Comment by richard67** [comment]
I can reproduce that with my demo's index.html when remoding the `<title>`tag from the head.
I think the error happens when getting the default value for the `data-title` option here: [https://github.com/heiseonline/shariff/blob/develop/src/js/shariff.js#L51](https://github.com/heiseonline/shariff/blob/develop/src/js/shariff.js#L51).

**Comment by richard67** [comment]
@pxamike Pull request with a correction for this issue is #295 . Can you test as described there and let us know in comment a comment there if it works for you?

**Comment by richard67** [comment]
@pxamike I have meanwhile build packages with a correction. You can find them in the testing instructions of #295 in section "Method 2". Can you test?

**Comment by pxamike** [comment]
@richard67 testing done. thanks for the fix. :)

**Comment by pxamike** [comment]
thanks, I guess this one can be closed. :)
