### ISSUE TITLE
XING share button not working

### ISSUE THREAD

**Issue by neffets** [heiseonline/shariff#353]
The share button for XING is not working anymore.

The old url: https://www.xing.com/social_plugins/share?url=
gives "not found"
New url for static share link is:  https://www.xing.com/spi/shares/new?url=

**Comment by richard67** [comment]
@neffets I can't confirm that the link in Shariff is not working.

However, I can confirm that the new URL which you provide is equal to what [https://github.com/vinkla/shareable-links/blob/master/README.md#xing](https://github.com/vinkla/shareable-links/blob/master/README.md#xing), my favourite source for sharing links, sais.

There is also a link to the Xing documentation, which sais the same in section "Share on XING with custom design": [https://dev.xing.com/plugins/share_button/docs](https://dev.xing.com/plugins/share_button/docs).

Maybe the Shariff link still works for me because Xing has some kind of redirect?

Anyway, it seems you are right, and I will make a pull request (PR) to correct the link.

**Comment by richard67** [comment]
@neffets Pull request (PR) is #354 . Could you test as described there, and if test is successful close this issue?
If not, wait until the maintainers have made a new release of Shariff which includes the change from my PR, then update your Shariff to the new release, and then if all is ok close this issue if it is still open.

**Comment by neffets** [comment]
patch-1 from #354 is working

**Comment by richard67** [comment]
You can close this issue now. The correction is included in the new release 3.2.0 from yesterday, April 1, 2019.

**Comment by richard67** [comment]
@compeak This issue can be closed since it was corrected with #354 and released with 3.2.0.

**Comment by neffets** [comment]
In 3.2.0 working - Thanx
