### ISSUE TITLE
Docs: Provide Custom-Build instructions

### ISSUE THREAD

**Issue by staabm** [heiseonline/shariff#52]
Atm shariff-complete is a whopping ~125kb fat lib.

For most websites you only need a few out of all supported social-media services, so it would be awesome if you could provide instructions on how to build shariff for such a website.

**Comment by pmb0** [comment]
See https://github.com/pmb0/shariff-integration for a custom build example.

**Comment by craiq** [comment]
big css is because of complete implementation of font awesome
and big js is because of implementation of jquery
the services take the least space
from font awesome you just need very little, but you have to change several lines, when you want to do this.
when you already have jquery, you can use the small js

How to build:
install node.js
run in the shariff-folder with your console:
npm install
grunt build
