### ISSUE TITLE
Icons not shown on Firfefox with HTTPS Everywhere Add-on

### ISSUE THREAD

**Issue by mdsoft** [heiseonline/shariff#76]
I ran into a complex issue I can't solve myself.

The setting:
Firefox 38.0.1
HTTPS Everywhere Add-on 5.0.5
shariff 1.13.0

The problem:
The shariff icons are not displayed on the sharing buttons on my website while HTTPS Everywhere is activated:
http://alpenwetter.md-soft.info/

![shariff_without_icons](https://cloud.githubusercontent.com/assets/5264836/7879379/3e73c1f0-05f0-11e5-9064-4f6922b00dc6.png)

After disabling HTTPS Everywhere, the icons are shown on the sharing buttons without problem.

The shariff demo site works without problems with activated HTTPS Everywhere Firefox add-on.
https://heiseonline.github.io/shariff/

Thus the problem might be a specific interference on my website(s).
Does anyone have a hint, how I can solve this problem?

**Comment by craiq** [comment]
you can try to update your jquery. use 1.11.2

**Comment by kraftner** [comment]
Same issue with jQuery 1.11.3.

For some reason that happens only on first load.

**Comment by kraftner** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/2425

**Comment by kraftner** [comment]
The reason this is working on the demo site is that it isn't using a plain shariff version but [one that includes a locally hosted fontawesome](https://github.com/heiseonline/shariff/blob/2f405af555edc7350d2eced1b5c5d40e8f719da3/app.min.css) and not a CDN hosted one.

I think this issue was introduced when switching to a CDN here: 
92c279bafa19854200827fe07fc449f985ba86a8 and fcf110954ae57303dc32c8cdc7c2737f8bd51b43

On to the cause of the issue: Firefox is throwing cross origin errors so the problem seems to be the fact that protocol relative urls are being used: [`//netdna.bootstrapcdn.com/font-awesome/...`](https://github.com/heiseonline/shariff/blob/b7287ef1655e8b4890eb705666b07898f16b570e/Gruntfile.js#L127)

I'd propose switching to always using https as this this [has no practical downsides](http://www.paulirish.com/2010/the-protocol-relative-url/).
