### ISSUE TITLE
Using Pinterest widget HTML on page breaks Shariff's Pinterest button

### ISSUE THREAD

**Issue by hzulla** [heiseonline/shariff#86]
Pinterest recommends using this HTML to embed a widget on its page:

![pinterest](https://cloud.githubusercontent.com/assets/1705654/8183704/2c2e4198-143a-11e5-8e79-2f4ba4be51e8.png)

    <a data-pin-do="embedUser" href="http://de.pinterest.com/kitchennerds/"></a>
    
    <script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>

However, calling pinit.js will break the Shariff Pinterest button when used on the same page. After its deferred execution, it replaces the Pinterest button in Shariff and the *Wordpress Shariff Wrapper* plugin will look like this:

![shariff](https://cloud.githubusercontent.com/assets/1705654/8183713/3747ef8e-143a-11e5-8c2c-65bda2ebc36d.png)

**Comment by startef** [comment]
Hi hzulla,

I'm one of the developers of the WordPress plugin you seem to be using. First off: Using an original Pinterest script kind of defeats the purpose of the Shariff buttons, because now your widget sends data about your visitors to Pinterest. So in the spirit of the Shariff idea, it is not wise to use other scripts on your page that do not respect the privacy of your visitors.

Nevertheless, I just committed a fix for this problem to our plugin as well as to the original Shariff code. The update should be pushed to wordpress.org very soon.

JP

**Comment by hzulla** [comment]
Hi,

> First off: Using an original Pinterest script kind of defeats the purpose of the Shariff buttons

Yes, I'm aware of that. Still, thank you very much for fixing this.
